# Generated by Django 4.0.6 on 2022-07-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='roastery',
            options={'verbose_name_plural': 'roasteries'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'varieties'},
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='frontend.country'),
            preserve_default=False,
        ),
    ]
