# Generated by Django 4.0.6 on 2022-07-13 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_coffee_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.country'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='elevation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='farmer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.farmer'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='processing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.processing'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.region'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='roast_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date roasted'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='variety',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.variety'),
        ),
    ]
